document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("  <meta charset=\'UTF-8\'>");
document.writeln("  <style>");
document.writeln("  </style>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.bootcss.com/twitter-bootstrap/2.3.2/css/bootstrap.min.css\' rel=\'external nofollow\' >");
document.writeln("  <script src=\'http://libs.baidu.com/jquery/1.7.2/jquery.min.js\'></script>");
document.writeln("  <script src=\'https://cdn.bootcss.com/twitter-bootstrap/2.3.2/js/bootstrap.js\'></script>");
document.writeln("	<link rel=\'stylesheet\' type=\'text/css\' href=\'css/header.css\' />");
document.writeln("	<link rel=\'stylesheet\' type=\'text/css\' href=\'css/font.css\' />");
document.writeln("	<script type=\'text/javascript\'>");
document.writeln("   $(document).ready(function(){");
document.writeln("		var type=localStorage.getItem(\'type\');");
document.writeln("		if(type==0){");
document.writeln("				document.getElementById(\'abount\').innerHTML =\'ABOUT\';");
document.writeln("				document.getElementById(\'abount\').setAttribute(\'class\', \'head-a font1\'); ");
document.writeln("				document.getElementById(\'design\').innerHTML =\'DESIGN\';");
document.writeln("				document.getElementById(\'design\').setAttribute(\'class\', \'head-a font1\'); ");
document.writeln("				document.getElementById(\'drawing\').innerHTML =\'DRAWING\';");
document.writeln("				document.getElementById(\'logo\').innerHTML =\'LOGO\';");
document.writeln("				document.getElementById(\'project\').innerHTML =\'PROJECT\';");
document.writeln("				document.getElementById(\'photography\').innerHTML =\'PHOTOGRAPHY\';");
document.writeln("				document.getElementById(\'photography\').setAttribute(\'class\', \'head-a font1\'); ");
document.writeln("				document.getElementById(\'contact\').innerHTML =\'CONTACT\';");
document.writeln("				document.getElementById(\'contact\').setAttribute(\'class\', \'head-a font1\'); ");
document.writeln("				var div=document.getElementById(\'selectUl\');");
document.writeln("			}");
document.writeln("			if(type==1){");
document.writeln("				document.getElementById(\'abount\').innerHTML =\'简介\';");
document.writeln("				document.getElementById(\'abount\').setAttribute(\'class\', \'head-a font4\'); ");
document.writeln("				document.getElementById(\'design\').innerHTML =\'作品\';");
document.writeln("				document.getElementById(\'design\').setAttribute(\'class\', \'head-a font4\'); ");
document.writeln("				document.getElementById(\'drawing\').innerHTML =\'绘画\';");
document.writeln("				document.getElementById(\'logo\').innerHTML =\'徽标\';");
document.writeln("				document.getElementById(\'project\').innerHTML =\'系列\';");
document.writeln("				document.getElementById(\'photography\').innerHTML =\'摄影\';");
document.writeln("				document.getElementById(\'photography\').setAttribute(\'class\', \'head-a font4\'); ");
document.writeln("				document.getElementById(\'contact\').innerHTML =\'联系我们\';");
document.writeln("				document.getElementById(\'contact\').setAttribute(\'class\', \'head-a font4\'); ");
document.writeln("				var div=document.getElementById(\'selectUl\');");
document.writeln("			}");
document.writeln("});");
document.writeln("		// 第三种 通过方法响应点击事件");
document.writeln("		function upssion(type){");
document.writeln("			localStorage.setItem(\'type\', type)");
document.writeln("			if(type==0){");
document.writeln("				document.getElementById(\'abount\').innerHTML =\'ABOUT\';");
document.writeln("				document.getElementById(\'abount\').setAttribute(\'class\', \'head-a font1\'); ");
document.writeln("				document.getElementById(\'design\').innerHTML =\'DESIGN\';");
document.writeln("				document.getElementById(\'design\').setAttribute(\'class\', \'head-a font1\'); ");
document.writeln("				document.getElementById(\'drawing\').innerHTML =\'DRAWING\';");
document.writeln("				document.getElementById(\'logo\').innerHTML =\'LOGO\';");
document.writeln("				document.getElementById(\'project\').innerHTML =\'PROJECT\';");
document.writeln("				document.getElementById(\'photography\').innerHTML =\'PHOTOGRAPHY\';");
document.writeln("				document.getElementById(\'photography\').setAttribute(\'class\', \'head-a font1\'); ");
document.writeln("				document.getElementById(\'contact\').innerHTML =\'CONTACT\';");
document.writeln("				document.getElementById(\'contact\').setAttribute(\'class\', \'head-a font1\'); ");
document.writeln("				var div=document.getElementById(\'selectUl\');");
document.writeln("				");
document.writeln("			}");
document.writeln("			if(type==1){");
document.writeln("				document.getElementById(\'abount\').innerHTML =\'简介\';");
document.writeln("				document.getElementById(\'abount\').setAttribute(\'class\', \'head-a font4\'); ");
document.writeln("				document.getElementById(\'design\').innerHTML =\'作品\';");
document.writeln("				document.getElementById(\'design\').setAttribute(\'class\', \'head-a font4\'); ");
document.writeln("				document.getElementById(\'drawing\').innerHTML =\'绘画\';");
document.writeln("				document.getElementById(\'logo\').innerHTML =\'徽标\';");
document.writeln("				document.getElementById(\'project\').innerHTML =\'系列\';");
document.writeln("				document.getElementById(\'photography\').innerHTML =\'摄影\';");
document.writeln("				document.getElementById(\'photography\').setAttribute(\'class\', \'head-a font4\'); ");
document.writeln("				document.getElementById(\'contact\').innerHTML =\'联系我们\';");
document.writeln("				document.getElementById(\'contact\').setAttribute(\'class\', \'head-a font4\'); ");
document.writeln("				var div=document.getElementById(\'selectUl\');");
document.writeln("");
document.writeln("");
document.writeln("			}");
document.writeln("		}");
document.writeln("");
document.writeln("		function toAbount(){");
document.writeln("			var type=localStorage.getItem(\'type\');");
document.writeln("			window.location.href=\'about.html?type=\'+type;");
document.writeln("		}");
document.writeln("		function toContact(){");
document.writeln("			var type=localStorage.getItem(\'type\');");
document.writeln("			window.location.href=\'contact.html?type=\'+type;");
document.writeln("		}");
document.writeln("		");
document.writeln("");
document.writeln("</script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("  <div class=\'tabbable\'> <!-- Only required for left/right tabs -->");
document.writeln("    <ul class=\'row head-ul\'>");
document.writeln("      <li class=\'span3 head-li\' style=\'margin-top: 0px;\'><a onclick=\'history.back(-1)\' ><img width=\'160px\' src=\'img/header/MZ.png\'></a></li>");
document.writeln("      <li  class=\'span3 head-li\'><a  id=\'abount\'  class=\'head-a font1\' onclick=\'toAbount()\' >ABOUT</a></li>");
document.writeln("	  <li class=\'span3 head-li\'>");
document.writeln("		  <div class=\'dropdown\'>");
document.writeln("		      <a id=\'design\'  class=\'head-a font1 dropdown-toggle\' id=\'dropdownMenu1\' data-toggle=\'dropdown\'>DESIGN");
document.writeln("		      </a>");
document.writeln("		      <ul id=\'selectUl\' class=\'dropdown-menu\' role=\'menu\' aria-labelledby=\'dropdownMenu1\' style=\'background: #999;    margin-left: 50px;\'>");
document.writeln("				  <li role=\'presentation\' style=\'text-align: center;font-size: 20px;margin-top: 10px;\' >");
document.writeln("				      <a class=\' font2\' id=\'drawing\' style=\'color: #f5f5f5\' role=\'menuitem\' tabindex=\'-1\' href=\'drawing.html\'>DRAWING</a>");
document.writeln("				  </li>");
document.writeln("				  <li role=\'presentation\' style=\'text-align: center;font-size: 20px;margin-top: 10px;\' >");
document.writeln("						<a class=\' font2\'  id=\'logo\' style=\'color: #f5f5f5\' role=\'menuitem\' tabindex=\'-1\' href=\'logo.html\'>LOGO</a>");
document.writeln("		          </li>");
document.writeln("							<li role=\'presentation\' style=\'text-align: center;font-size: 20px;margin-top: 10px;margin-bottom: 10px;\' >");
document.writeln("								<a class=\' font2\' id=\'project\' style=\'color: #f5f5f5\' role=\'menuitem\' tabindex=\'-1\' href=\'project.html\'>PROJECT</a>");
document.writeln("		          </li>");
document.writeln("");
document.writeln("		      </ul>");
document.writeln("		  </div>");
document.writeln("		  ");
document.writeln("	  </li>");
document.writeln("	  <li class=\'span3 head-li\'><a id=\'photography\' class=\'head-a font1\' href=\'photography.html\' >PHOTOGRAPHY</a></li>");
document.writeln("	  <li class=\'span3 head-li\'><a  id=\'contact\' class=\'head-a font1\' onclick=\'toContact()\' >CONTACT</a></li>");
document.writeln("		<li class=\'span3 head-li\' style=\'text-align: right;\'><a  class=\'head-a font3\' onclick=\'upssion(0)\' >ENG</a>");
document.writeln("			<a class=\'head-a font3\' >|</a>");
document.writeln("			<a class=\'head-a font3\' onclick=\'upssion(1)\' >中文</a></li>");
document.writeln("    </ul>");
document.writeln("  </div>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");
document.writeln("");